targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - test/_support/*
          - example/lib/models/*
      flutter_data|data_repository_builder:
        generate_for:
          - test/_support/*
          - example/lib/models/*
      flutter_data|data_library_intermediate_builder:
        generate_for:
          - test/_support/*
          - example/lib/models/*
      flutter_data|data_library_builder:
        generate_for:
          - /*
          - example/*
      isar|isar_generator:
        enabled: false

builders:
  data_repository_builder:
    import: "package:flutter_data/builders/repository_builder.dart"
    builder_factories: ["repositoryBuilder"]
    build_extensions: { ".dart": [".flutter_data.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    required_inputs: [".freezed.dart"]

  data_library_intermediate_builder:
    import: "package:flutter_data/builders/data_library_builder.dart"
    builder_factories: ["dataExtensionIntermediateBuilder"]
    build_extensions: { ".dart": [".flutter_data.info"] }
    auto_apply: dependents
    build_to: cache
    runs_before: ["data_library_builder"]

  data_library_builder:
    import: "package:flutter_data/builders/data_library_builder.dart"
    builder_factories: ["dataExtensionBuilder"]
    build_extensions: { ".flutter_data.info": [".dart"] }
    auto_apply: dependents
    required_inputs: [".flutter_data.info"]
    build_to: source
