name: flutter_data_generator
description: Code generation of flutter_data
version: 1.0.1
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  analyzer: ^3.0.0
  build: ^2.0.2
  build_resolvers: ^2.0.3
  flutter_data: ^1.0.0
  glob: ^2.0.0
  pubspec_parse: ^1.0.0
  source_gen: ^1.2.1
dependency_overrides:
  flutter_data:
   path: ../flutter_data