name: flutter_data
description: >
  The seamless way to work with persistent data models in Flutter. Inspired by
  Ember Data and ActiveRecord.
version: 1.0.1
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  async: ^2.8.2
  collection: ^1.15.0
  crypto: ^3.0.1
  equatable: ^2.0.3
  hive: ^2.0.5
  http: ^0.13.4
  inflection3: ^0.5.3+2
  meta: ^1.7.0
  path: ^1.8.1
  riverpod: ^1.0.3
  state_notifier: ^0.7.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.3
  matcher: ^0.12.11
  mockito: ^5.0.17
  source_gen_test: ^1.0.2
  test: ^1.20.1
  test_cov: ^1.0.1
  very_good_analysis: ^2.4.0
