name: flutter_data
description: >
  The seamless way to work with persistent data models in Flutter. Inspired by
  Ember Data and ActiveRecord.
version: 1.0.1
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  async: ^2.6.1
  build: ^2.0.2
  build_resolvers: ^2.0.3
  collection: ^1.15.0
  crypto: ^3.0.1
  equatable: ^2.0.3
  glob: ^2.0.1
  hive: ^2.0.4
  http: ^0.13.3
  inflection3: ^0.5.3+2
  meta: ^1.7.0
  path: ^1.8.0
  pubspec_parse: ^1.0.0
  riverpod: ^1.0.0
  source_gen: ^1.0.1
  state_notifier: ^0.7.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  json_serializable: ^6.0.1
  matcher: ^0.12.10
  mockito: ^5.0.9
  source_gen_test: ^1.0.0
  test: ^1.17.5
  test_cov: ^1.0.1
  very_good_analysis: ^2.4.0
