name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - windows
          - macos
          - web
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
            sdk: stable
          - platform: web
            os: ubuntu-latest
            dartTestArgs: -p chrome

    runs-on: ${{ matrix.os }}

    steps:
      - uses: dart-lang/setup-dart@v1.6.2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Generate coverage
        if: runner.os == 'macOS'
        run: dart run coverage:test_with_coverage
      - name: Send coverage report to codecov
        if: runner.os == 'macOS'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
